### ISSUE TITLE
No such file or directory: credentials.json

### ISSUE THREAD

**Issue by drKAIz** [Painezor/Toonbot#2]
![error](https://user-images.githubusercontent.com/32905161/37793101-76c7528e-2dec-11e8-9554-032d94d56576.png)
I seem to be getting this error whenever I try to run 'core.py'. Would you happen to know what the problem is? Also, where would I insert the token?

**Comment by Painezor** [comment]
The credentials file is basically a dictionary of tokens for various websites. While the bot is open source, my tokens are not so they're .gitignored.
