### ISSUE TITLE
How does one run the bot?

### ISSUE THREAD

**Issue by DontPanic330** [Painezor/Toonbot#3]
Hi,

1. I'm trying to run the bot but it's not clear to me what the requirements are for running the bot.

2. How do I set up the json config file? Can you show an example?

3. I've seen the bot on other servers, after running it - How does one setup the auto-update feature for stuff like Live Scores, Transfer-Ticker?

Thanks

**Comment by J0hnd0euf** [comment]
Hello did you find a way to make it work? 

I can use the commands -scores and all but i can't find a way to have Live scores updating by himself (like here : https://imgur.com/avwV72r)

**Comment by Painezor** [comment]
just invite him to your server, find one he's on or come to discord.gg/a5NHvPx  and use .tb hello to get the invite link 

Running him yourself would require having my database.
