### ISSUE TITLE
Is there a way to automate commands? 

### ISSUE THREAD

**Issue by DemetriussXVII** [Painezor/Toonbot#5]
Let's say that I want to setup a channel for match results or transfers, is there a way to make the bot report on concurrent match results including any updates automatically as it occur?

**Comment by Painezor** [comment]
The livescores channel can be configured to recieve live scores for any leagues, as it's own dedicated channel.

Transfer tickers can be output in any channel(s)

I have future plans to bring back the old goal ticker I had but it would need to be converted to use my new code structure and I'd need to set up the database for users to filter what they want. Tagging this as feature request.

**Comment by Painezor** [comment]
Ticker is in place.
